### ISSUE TITLE
upgrading baseline jenkins from 1.618 to 1.641 for security fixes

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi-Plugins-Starter-Pack#9]
Jenkins needs to be upgrade for the following security fixes
 * as-of 1.638 - https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-11-11
 * as-of 1.641 - https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-12-09

I get the following maven comple error
```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
Found Banned Dependency: org.sonatype.sisu:sisu-guice:jar:3.0.1
```

if I adjust this plugin to account for the __core/pom.xml__ changes between https://github.com/jenkinsci/jenkins/compare/jenkins-1.628...jenkins-1.641
```
     <dependency>
       <groupId>org.jenkins-ci</groupId>
       <artifactId>bytecode-compatibility-transformer</artifactId>
-      <version>1.5</version>
+      <version>1.8</version>
     </dependency>
     <dependency>
       <groupId>org.jenkins-ci</groupId>
@@ -514,7 +514,7 @@ THE SOFTWARE.
     <dependency>
       <groupId>net.java.dev.jna</groupId>
       <artifactId>jna</artifactId>
-      <version>4.1.0</version>
+      <version>4.2.1</version>
     </dependency>
```

**Comment by vvitayau** [comment]
If edit pom.xml to add the following exclusion as part of cobertura plugin
```
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>cobertura</artifactId>
            <version>1.9.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.sonatype.sisu</groupId>
                    <artifactId>sisu-guice</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Then compilation proceeds but then I get the following test failures
```
-------------------------------------------------------
Running com.groupon.jenkins.dotci.listeners.DotCiProjectSetupListenerTest
Running com.groupon.jenkins.dotci.notifiers.HipchatNotifierTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.591 sec <<< FAILURE! - in com.groupon.jenkins.dotci.notifiers.HipchatNotifierTest
should_post_failure_message_on_failed_build_in_specified_hipchat_room(com.groupon.jenkins.dotci.notifiers.HipchatNotifierTest)  Time elapsed: 0.375 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
	at org.apache.commons.httpclient.HttpClient.<clinit>(HttpClient.java:66)
	at sun.reflect.GeneratedSerializationConstructorAccessor3.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:56)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.jmock.ClassImposterizer.createProxy(ClassImposterizer.java:128)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:63)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:56)
	at org.mockito.internal.creation.CglibMockMaker.createMock(CglibMockMaker.java:23)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:26)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
	at org.mockito.Mockito.mock(Mockito.java:1243)
	at org.mockito.Mockito.mock(Mockito.java:1120)
	at com.groupon.jenkins.dotci.notifiers.HipchatNotifierTest.should_post_failure_message_on_failed_build_in_specified_hipchat_room(HipchatNotifierTest.java:32)

Running com.groupon.jenkins.dotci.notifiers.WebhookNotifierTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE! - in com.groupon.jenkins.dotci.notifiers.WebhookNotifierTest
should_make_a_post_to_web_hook_url_with_payload(com.groupon.jenkins.dotci.notifiers.WebhookNotifierTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.commons.httpclient.HttpClient$$EnhancerByMockitoWithCGLIB$$4ff770a1
	at sun.reflect.GeneratedSerializationConstructorAccessor3.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:56)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.jmock.ClassImposterizer.createProxy(ClassImposterizer.java:128)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:63)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:56)
	at org.mockito.internal.creation.CglibMockMaker.createMock(CglibMockMaker.java:23)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:26)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
	at org.mockito.Mockito.mock(Mockito.java:1243)
	at org.mockito.Mockito.mock(Mockito.java:1120)
	at com.groupon.jenkins.dotci.notifiers.WebhookNotifierTest.should_make_a_post_to_web_hook_url_with_payload(WebhookNotifierTest.java:53)

Running com.groupon.jenkins.dotci.plugins.JunitPluginAdapterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec - in com.groupon.jenkins.dotci.plugins.JunitPluginAdapterTest
Running InjectedTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.071 sec - in com.groupon.jenkins.dotci.listeners.DotCiProjectSetupListenerTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.753 sec <<< FAILURE! - in InjectedTest
initializationError(InjectedTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:310)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
	at org.apache.commons.beanutils.ConvertUtilsBean.<init>(ConvertUtilsBean.java:157)
	at org.kohsuke.stapler.Stapler.<clinit>(Stapler.java:1080)
	at hudson.model.Node$Mode.<clinit>(Node.java:550)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.lang.Class.getEnumConstantsShared(Class.java:3138)
	at java.lang.Class.getEnumConstants(Class.java:3116)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:4310)
	at hudson.PluginManager.<clinit>(PluginManager.java:1257)
	at org.jvnet.hudson.test.HudsonTestCase.<init>(HudsonTestCase.java:272)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite$1.<init>(JellyTestSuiteBuilder.java:139)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.<init>(JellyTestSuiteBuilder.java:139)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.<init>(JellyTestSuiteBuilder.java:138)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder.build(JellyTestSuiteBuilder.java:80)
	at org.jvnet.hudson.test.PluginAutomaticTestBuilder.build(PluginAutomaticTestBuilder.java:58)
	at InjectedTest.suite(InjectedTest.java:15)


Results :

Tests in error:
  HipchatNotifierTest.should_post_failure_message_on_failed_build_in_specified_hipchat_room:32 » NoSuchMethod
  WebhookNotifierTest.should_make_a_post_to_web_hook_url_with_payload:53 » NoClassDefFound
  InjectedTest.suite:15 » ExceptionInInitializer

Tests run: 7, Failures: 0, Errors: 3, Skipped: 0
```

**Comment by vvitayau** [comment]
I'm now suspicious of cobertura use of maven-plugin. I would recommend only using maven-plugin 2.1+ because below that has not been properly tagged in repo.

https://github.com/jenkinsci/maven-plugin/blob/maven-plugin-2.12.1/pom.xml#L262-L280

**Comment by vvitayau** [comment]
Closing this issue ... it helped me discover the two PR above
